### ISSUE TITLE
Hardcoded path for win32yark

### ISSUE THREAD

**Issue by gabrielmocanu** [bogdan-calapod/nvim-dotfiles#1]
[This] might be a problem because lazy-vim doesn't install win32yark by default.
I guess the path should be smth like: `/home/$USER/.local/bin/win32yank.exe` but some kind of script needs to download the `.exe` file before.
With this configuration, it throws an error every time you yank.

[This]: https://github.com/bogdan-calapod/nvim-dotfiles/blob/dd737b9e2d36636b82af527551dd7f2165aa1cfd/lua/config/options.lua#L18

**Comment by bogdan-calapod** [comment]
Lol - thanks for the heads up :))
